---
server.name: kibana
server.host: 0.0.0.0
server.publicBaseUrl: "${KIBANA_URL}"

# Elasticsearch settings
elasticsearch.hosts: [ "https://elasticsearch1.elasticsearch:9200", "https://elasticsearch2.elasticsearch:9200", "https://elasticsearch3.elasticsearch:9200"]
elasticsearch.ssl.certificateAuthorities: [ "${CONFIG_DIR}/ca.crt" ]
elasticsearch.ssl.verificationMode: certificate
elasticsearch.username: "${KIBANA_USERNAME}"
elasticsearch.password: "${KIBANA_PASSWORD}"
# elasticsearch.serviceAccountToken: "${ELASTIC_SERVICE_ACCOUNT_TOKEN}"

# Elasticsearch monitoring settings
monitoring.ui.container.elasticsearch.enabled: true

# X-Pack Security
xpack.encryptedSavedObjects.encryptionKey: "${ENCRYPTION_KEY}"
xpack.security.encryptionKey: "${ENCRYPTION_KEY}"
xpack.reporting.encryptionKey: "${ENCRYPTION_KEY}"

# SSL settings
server.ssl.enabled: true
server.ssl.certificate: "${CONFIG_DIR}/kibana.crt"
server.ssl.key: "${CONFIG_DIR}/kibana.key"
server.ssl.certificateAuthorities: [ "${CONFIG_DIR}/ca.crt" ]

# fleet settings for Elastic-agent
# xpack.fleet.enabled: true
# xpack.fleet.agents.enabled: true
# xpack.fleet.agents.tlsCheckDisabled: true
# xpack.fleet.agents.kibana.host: "https://kibana:5601"
# xpack.fleet.agents.elasticsearch.host: "https://elasticsearch:9200"

# xpack.ingestManager.enabled: true
# xpack.ingestManager.fleet.enabled: true